server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/**,/staff/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#this is okta we can delete this
okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7w65a24Px90yms5d7
    client-secret: JfsTTqODW21
    scopes: 
      - openid
      - profile
      - email
      - offline_access
